CREATE TABLE IF NOT EXISTS CarDamage (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    tyresWearRL FLOAT,
    tyresWearRR FLOAT,
    tyresWearFL FLOAT,
    tyresWearFR FLOAT,
    tyresDamageRL SMALLINT,
    tyresDamageRR SMALLINT,
    tyresDamageFL SMALLINT,
    tyresDamageFR SMALLINT,
    brakesDamageRL SMALLINT,
    brakesDamageRR SMALLINT,
    brakesDamageFL SMALLINT,
    brakesDamageFR SMALLINT,
    frontLeftWingDamage SMALLINT,
    frontRightWingDamage SMALLINT,
    rearWingDamage SMALLINT,
    floorDamage SMALLINT,
    diffuserDamage SMALLINT,
    sidepodDamage SMALLINT,
    drsFault SMALLINT,
    ersFault SMALLINT,
    gearBoxDamage SMALLINT,
    engineDamage SMALLINT,
    engineMGUHWear SMALLINT,
    engineESWear SMALLINT,
    engineCEWear SMALLINT,
    engineICEWear SMALLINT,
    engineMGUKWear SMALLINT,
    engineTCWear SMALLINT,
    engineBlown SMALLINT,
    engineSeized SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);