CREATE TABLE IF NOT EXISTS CarSetup (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    frontWing SMALLINT,
    rearWing SMALLINT,
    onThrottle SMALLINT,
    offThrottle SMALLINT,
    frontCamber FLOAT,
    rearCamber FLOAT,
    frontToe FLOAT,
    rearToe FLOAT,
    frontSuspension SMALLINT,
    rearSuspension SMALLINT,
    frontAntiRollBar SMALLINT,
    rearAntiRollBar SMALLINT,
    frontSuspensionHeight SMALLINT,
    rearSuspensionHeight SMALLINT,
    brakePressure SMALLINT,
    brakeBias SMALLINT,
    rearLeftTyrePressure FLOAT,
    rearRightTyrePressure FLOAT,
    frontLeftTyrePressure FLOAT,
    frontRightTyrePressure FLOAT,
    ballast SMALLINT,
    fuelLoad FLOAT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);