CREATE TABLE IF NOT EXISTS CarMotion (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    worldPositionX FLOAT,
    worldPositionY FLOAT,
    worldPositionZ FLOAT,
    worldVelocityX FLOAT,
    worldVelocityY FLOAT,
    worldVelocityZ FLOAT,
    worldForwardDirX SMALLINT,
    worldForwardDirY SMALLINT,
    worldForwardDirZ SMALLINT,
    worldRightDirX SMALLINT,
    worldRightDirY SMALLINT,
    worldRightDirZ SMALLINT,
    gForceLateral FLOAT,
    gForceLongitudinal FLOAT,
    gForceVertical FLOAT,
    yaw FLOAT,
    pitch FLOAT,
    roll FLOAT,
    lat FLOAT,
    lon FLOAT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);