CREATE TABLE IF NOT EXISTS CarTelemetry (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    speed INTEGER,
    throttle FLOAT,
    steer FLOAT,
    brake FLOAT,
    clutch SMALLINT,
    gear TINYINT,                      -- 保留 TINYINT（可能为 -1 表示空挡/无效）
    engineRPM INTEGER,
    drs SMALLINT,
    revLightsPercent SMALLINT,
    revLightsBitValue INTEGER,
    brakesTemperatureRL INTEGER,
    brakesTemperatureRR INTEGER,
    brakesTemperatureFL INTEGER,
    brakesTemperatureFR INTEGER,
    tyresSurfaceTemperatureRL SMALLINT,
    tyresSurfaceTemperatureRR SMALLINT,
    tyresSurfaceTemperatureFL SMALLINT,
    tyresSurfaceTemperatureFR SMALLINT,
    tyresInnerTemperatureRL SMALLINT,
    tyresInnerTemperatureRR SMALLINT,
    tyresInnerTemperatureFL SMALLINT,
    tyresInnerTemperatureFR SMALLINT,
    engineTemperature INTEGER,
    tyresPressureRL FLOAT,
    tyresPressureRR FLOAT,
    tyresPressureFL FLOAT,
    tyresPressureFR FLOAT,
    surfaceTypeRL SMALLINT,
    surfaceTypeRR SMALLINT,
    surfaceTypeFL SMALLINT,
    surfaceTypeFR SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);