CREATE TABLE IF NOT EXISTS CarStatus (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    tractionControl SMALLINT,
    antiLockBrakes SMALLINT,
    fuelMix SMALLINT,
    fuelMixInStr CHAR(10),
    frontBrakeBias SMALLINT,
    pitLimiterStatus SMALLINT,
    fuelInTank FLOAT,
    fuelCapacity FLOAT,
    fuelRemainingLaps FLOAT,
    maxRPM INTEGER,
    idleRPM INTEGER,
    maxGears SMALLINT,
    drsAllowed SMALLINT,
    drsActivationDistance INTEGER,
    actualTyreCompound SMALLINT,
    visualTyreCompound SMALLINT,
    tyresAgeLaps SMALLINT,
    vehicleFiaFlags TINYINT,          -- 注意：原字段无 UNSIGNED，保留 TINYINT
    vehicleFiaFlagsInStr CHAR(10),
    ersStoreEnergy FLOAT,
    ersDeployMode SMALLINT,
    ersDeployModeInStr CHAR(10),
    ersHarvestedThisLapMGUK FLOAT,
    ersHarvestedThisLapMGUH FLOAT,
    ersDeployedThisLap FLOAT,
    networkPaused SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);