CREATE TABLE IF NOT EXISTS FinalClassification (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    teamName VARCHAR(16),
    position SMALLINT,
    numLaps SMALLINT,
    gridPosition SMALLINT,
    points SMALLINT,
    numPitStops SMALLINT,
    resultStatus SMALLINT,
    resultStatusStr VARCHAR(16),
    bestLapTime BIGINT,
    bestLapTimeStr VARCHAR(16),
    totalRaceTime DOUBLE,
    totalRaceTimeStr VARCHAR(16),
    penaltiesTime SMALLINT,
    numPenalties SMALLINT,
    numTyreStints SMALLINT,
    tyreStintsVisual VARCHAR(256),
    overallResult VARCHAR(32),
    PRIMARY KEY (ipDecimal, beginUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);