CREATE TABLE IF NOT EXISTS LapDetails (
    ipDecimal INT UNSIGNED,
    beginUnixTime INT UNSIGNED,
    curUnixTime INT UNSIGNED,
    curTime DATETIME,
    carIndex TINYINT UNSIGNED,
    driverName VARCHAR(48),
    currentLapNum TINYINT UNSIGNED,
    lapDistance INT UNSIGNED,
    speed SMALLINT UNSIGNED,
    throttle FLOAT,
    steer FLOAT,
    brake FLOAT,
    clutch TINYINT UNSIGNED,
    gear TINYINT,
    engineRPM SMALLINT UNSIGNED,
    drs TINYINT UNSIGNED,
    worldPositionX FLOAT,
    worldPositionY FLOAT,
    worldPositionZ FLOAT,
    currentLapTimeInMS INT UNSIGNED,
    currentLapTimeInStr VARCHAR(16),
    ersDeployMode TINYINT UNSIGNED,
    PRIMARY KEY(
        ipDecimal,
        beginUnixTime,
        driverName,
        currentLapNum,
        lapDistance
    ),
    FOREIGN KEY(ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime) ON DELETE CASCADE
);