CREATE TABLE IF NOT EXISTS LapDetails (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    currentLapNum SMALLINT,
    lapDistance BIGINT,
    speed INTEGER,
    throttle FLOAT,
    steer FLOAT,
    brake FLOAT,
    clutch SMALLINT,
    gear TINYINT,                      -- 保留 TINYINT（可能为 -1）
    engineRPM INTEGER,
    drs SMALLINT,
    worldPositionX FLOAT,
    worldPositionY FLOAT,
    worldPositionZ FLOAT,
    currentLapTimeInMS BIGINT,
    currentLapTimeInStr VARCHAR(16),
    ersDeployMode SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, driverName, currentLapNum, lapDistance),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);