CREATE TABLE IF NOT EXISTS LapData (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    teamName VARCHAR(16),
    lastLapTimeInMS BIGINT,
    lastLapTimeInStr VARCHAR(16),
    currentLapTimeInMS BIGINT,
    currentLapTimeInStr VARCHAR(16),
    sector1TimeInMS INTEGER,
    sector1TimeInStr VARCHAR(16),
    sector2TimeInMS INTEGER,
    sector2TimeInStr VARCHAR(16),
    lapDistance FLOAT,
    totalDistance FLOAT,
    safetyCarDelta FLOAT,
    carPosition SMALLINT,
    currentLapNum SMALLINT,
    pitStatus SMALLINT,
    pitStatusChar VARCHAR(12),
    numPitStops SMALLINT,
    sector SMALLINT,
    currentLapInvalid SMALLINT,
    penalties SMALLINT,
    warnings SMALLINT,
    numUnservedDriveThroughPens SMALLINT,
    numUnservedStopGoPens SMALLINT,
    gridPosition SMALLINT,
    driverStatus SMALLINT,
    driverStatusChar VARCHAR(10),
    resultStatus SMALLINT,
    resultStatusChar VARCHAR(16),
    pitLaneTimerActive SMALLINT,
    pitLaneTimeInLaneInMS INTEGER,
    pitStopTimerInMS INTEGER,
    pitStopShouldServePen SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);