CREATE TABLE IF NOT EXISTS Participants (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    aiControlled SMALLINT,
    driverId SMALLINT,
    networkId SMALLINT,
    teamId SMALLINT,
    teamName VARCHAR(48),
    myTeam SMALLINT,
    raceNumber SMALLINT,
    nationality SMALLINT,
    nationalityName VARCHAR(20),
    yourTelemetry SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);