-- BestLap
CREATE TABLE IF NOT EXISTS BestLap (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    bestLapTimeLapNum SMALLINT,
    bestLapSector1TimeInMS INTEGER,
    bestLapSector1TimeInStr VARCHAR(16),
    bestLapSector2TimeInMS INTEGER,
    bestLapSector2TimeInStr VARCHAR(16),
    bestLapSector3TimeInMS INTEGER,
    bestLapSector3TimeInStr VARCHAR(16),
    bestLapTimeInMS BIGINT,
    bestLapTimeInStr VARCHAR(16),
    bestSector1LapNum SMALLINT,
    bestSector1TimeInMS INTEGER,
    bestSector1TimeInStr VARCHAR(16),
    bestSector2LapNum SMALLINT,
    bestSector2TimeInMS INTEGER,
    bestSector2TimeInStr VARCHAR(16),
    bestSector3LapNum SMALLINT,
    bestSector3TimeInMS INTEGER,
    bestSector3TimeInStr VARCHAR(16),
    theoreticalBestLapTimeInMS BIGINT,
    theoreticalBestLapTimeInStr VARCHAR(16),
    PRIMARY KEY (ipDecimal, beginUnixTime, curUnixTime, carIndex),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);

-- LapHistoryData
CREATE TABLE IF NOT EXISTS LapHistoryData (
    ipDecimal BIGINT,
    beginUnixTime BIGINT,
    curUnixTime BIGINT,
    curTime DATETIME,
    carIndex SMALLINT,
    driverName VARCHAR(48),
    lapNum SMALLINT,
    sector1TimeInMS INTEGER,
    sector1TimeInStr VARCHAR(16),
    sector2TimeInMS INTEGER,
    sector2TimeInStr VARCHAR(16),
    sector3TimeInMS INTEGER,
    sector3TimeInStr VARCHAR(16),
    lapTimeInMS BIGINT,
    lapTimeInStr VARCHAR(16),
    lapValidBitFlags INTEGER,  -- 替代 BIT(4)
    tyreActualCompound BIGINT,
    tyreActualCompoundInStr CHAR(16),
    tyreVisualCompound BIGINT,
    tyreVisualCompoundInStr CHAR(16),
    tyreLapNumUsedInThisStint SMALLINT,
    PRIMARY KEY (ipDecimal, beginUnixTime, carIndex, lapNum),
    FOREIGN KEY (ipDecimal, beginUnixTime) REFERENCES SessionList(ipDecimal, beginUnixTime)
);